# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.smart_office_software_system.domain

# 端口
server:
  port: 8080

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_office_software?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 邮箱服务配置
  # 给自己的邮箱开通smtp服务然后获取密码即可
  mail:
    host: smtp.163.com
    username:
    password:
    port: 465
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

  # Redis 配置
  redis:
    host: localhost
    port: 6379
    # password: your_redis_password
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 5s

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB

# 文件存储配置
file:
  upload-dir1: E:/smart_office_software/
  upload-dir2: /var/www/smart_office_software/uploads/


# 认证相关配置
auth:
  jwt:
    secret: "vAkBiz4nussJaN627U1CEB/sQit4Si1FZH8nB89z3RQ="
    expire-minutes: 120
  token:
    expire-minutes: 120
    prefix: "LOGIN:TOKEN:"
